name: 🐛 Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser (if UI), Node version, etc.
      placeholder: "macOS 14, Node.js 20, Chrome 122"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide steps and expected vs actual behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error: '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Please paste error logs or screenshots if available.
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate.
        - label: I have tested this on the latest version of the main branch.