name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Please describe your idea clearly.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the issue or limitation you're experiencing.
      placeholder: "It's hard to customize button styles consistently across components..."

  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: Describe what you would like to see implemented.
      placeholder: "Provide a new prop on the Button component to allow easier style extension."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried workarounds? What were the results?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This is not a duplicate of an existing issue.
        - label: I have clearly described the problem and solution.
        - label: I am willing to contribute this feature via PR.